base_config: ./fs2_orig.yaml

# special configs for diffspeech
task_cls: tasks.tts.diffspeech.DiffSpeechTask
lr: 0.001
timesteps: 100
K_step: 71
diff_loss_type: l1
diff_decoder_type: 'wavenet'
schedule_type: 'linear'
max_beta: 0.06

## model configs for diffspeech
dilation_cycle_length: 1
residual_layers: 20
residual_channels: 256
decay_steps: 50000
keep_bins: 80
#content_cond_steps: [ ] # [ 0, 10000 ]
#spk_cond_steps: [ ] # [ 0, 10000 ]
#gen_tgt_spk_id: -1



# training configs for diffspeech
#max_sentences: 48
#num_sanity_val_steps: 1
num_valid_plots: 10
use_gt_dur: false
use_gt_f0: false
use_energy_embed: false
#pitch_type: cwt
max_updates: 160000